name: build nginx
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - main
    paths:
      - arm/**
jobs:
  push:
    name: "pterodactyl-images:nginx_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - Arm64
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./nginx
          file: ./nginx/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/Terrible-creeper/pterodactyl-images:nginx_${{ matrix.tag }}
